#if !defined(AFX_STATUSBAR_H__21B9695D_AE27_4006_8D26_A0BBAD680334__INCLUDED_)
#define AFX_STATUSBAR_H__21B9695D_AE27_4006_8D26_A0BBAD680334__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CPanels;
class CPicture;
class COleFont;

/////////////////////////////////////////////////////////////////////////////
// CStatusBar1 wrapper class

class CStatusBar1 : public CWnd
{
protected:
	DECLARE_DYNCREATE(CStatusBar1)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0x8e3867a3, 0x8586, 0x11d1, { 0xb1, 0x6a, 0x0, 0xc0, 0xf0, 0x28, 0x36, 0x28 } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:

// Operations
public:
	CString GetSimpleText();
	void SetSimpleText(LPCTSTR lpszNewValue);
	long GetStyle();
	void SetStyle(long nNewValue);
	CPanels GetPanels();
	void SetRefPanels(LPDISPATCH newValue);
	long GetMousePointer();
	void SetMousePointer(long nNewValue);
	CPicture GetMouseIcon();
	void SetMouseIcon(LPDISPATCH newValue);
	void SetRefMouseIcon(LPDISPATCH newValue);
	BOOL GetShowTips();
	void SetShowTips(BOOL bNewValue);
	long GetOLEDropMode();
	void SetOLEDropMode(long nNewValue);
	BOOL GetEnabled();
	void SetEnabled(BOOL bNewValue);
	COleFont GetFont();
	void SetRefFont(LPDISPATCH newValue);
	long GetHWnd();
	void SetHWnd(long nNewValue);
	void Refresh();
	void OLEDrag();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_STATUSBAR_H__21B9695D_AE27_4006_8D26_A0BBAD680334__INCLUDED_)
