#if !defined(AFX_PANEL_H__3B49D606_3430_44DB_B4CE_193EC17C541A__INCLUDED_)
#define AFX_PANEL_H__3B49D606_3430_44DB_B4CE_193EC17C541A__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CPicture;

/////////////////////////////////////////////////////////////////////////////
// CPanel wrapper class

class CPanel : public COleDispatchDriver
{
public:
	CPanel() {}		// Calls COleDispatchDriver default constructor
	CPanel(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CPanel(const CPanel& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	long GetAlignment();
	void SetAlignment(long nNewValue);
	long GetAutoSize();
	void SetAutoSize(long nNewValue);
	long GetBevel();
	void SetBevel(long nNewValue);
	BOOL GetEnabled();
	void SetEnabled(BOOL bNewValue);
	short GetIndex();
	void SetIndex(short nNewValue);
	CString GetKey();
	void SetKey(LPCTSTR lpszNewValue);
	float GetLeft();
	void SetLeft(float newValue);
	float GetMinWidth();
	void SetMinWidth(float newValue);
	CPicture GetPicture();
	void SetRefPicture(LPDISPATCH newValue);
	long GetStyle();
	void SetStyle(long nNewValue);
	VARIANT GetTag();
	void SetTag(const VARIANT& newValue);
	CString GetText();
	void SetText(LPCTSTR lpszNewValue);
	CString GetToolTipText();
	void SetToolTipText(LPCTSTR lpszNewValue);
	BOOL GetVisible();
	void SetVisible(BOOL bNewValue);
	float GetWidth();
	void SetWidth(float newValue);
	void SetPicture(LPDISPATCH newValue);
	void SetRefTag(const VARIANT& newValue);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_PANEL_H__3B49D606_3430_44DB_B4CE_193EC17C541A__INCLUDED_)
