#if !defined(AFX_PANELS_H__50CBE1F7_3EC3_4973_AFA7_F6BD46880706__INCLUDED_)
#define AFX_PANELS_H__50CBE1F7_3EC3_4973_AFA7_F6BD46880706__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CPanel;

/////////////////////////////////////////////////////////////////////////////
// CPanels wrapper class

class CPanels : public COleDispatchDriver
{
public:
	CPanels() {}		// Calls COleDispatchDriver default constructor
	CPanels(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CPanels(const CPanels& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	short GetCount();
	void SetCount(short nNewValue);
	CPanel Add(VARIANT* Index, VARIANT* Key, VARIANT* Text, VARIANT* Style, VARIANT* Picture);
	void Clear();
	CPanel GetItem(VARIANT* Index);
	void SetRefItem(VARIANT* Index, LPDISPATCH newValue);
	void Remove(VARIANT* Index);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_PANELS_H__50CBE1F7_3EC3_4973_AFA7_F6BD46880706__INCLUDED_)
